/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionRouteImport } from './routes/session'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as PlaylistsIdRouteImport } from './routes/playlists.$id'
import { Route as LibraryNewRouteImport } from './routes/library/new'
import { Route as ViewCodeIndexRouteImport } from './routes/view/$code/index'
import { Route as PresentCodeIndexRouteImport } from './routes/present/$code/index'
import { Route as LibraryIdIndexRouteImport } from './routes/library/$id/index'
import { Route as LibraryIdEditRouteImport } from './routes/library/$id/edit'

const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIdRoute = PlaylistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlaylistsRoute,
} as any)
const LibraryNewRoute = LibraryNewRouteImport.update({
  id: '/library/new',
  path: '/library/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewCodeIndexRoute = ViewCodeIndexRouteImport.update({
  id: '/view/$code/',
  path: '/view/$code/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentCodeIndexRoute = PresentCodeIndexRouteImport.update({
  id: '/present/$code/',
  path: '/present/$code/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdIndexRoute = LibraryIdIndexRouteImport.update({
  id: '/library/$id/',
  path: '/library/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdEditRoute = LibraryIdEditRouteImport.update({
  id: '/library/$id/edit',
  path: '/library/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/session': typeof SessionRoute
  '/library/new': typeof LibraryNewRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/library': typeof LibraryIndexRoute
  '/library/$id/edit': typeof LibraryIdEditRoute
  '/library/$id': typeof LibraryIdIndexRoute
  '/present/$code': typeof PresentCodeIndexRoute
  '/view/$code': typeof ViewCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/session': typeof SessionRoute
  '/library/new': typeof LibraryNewRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/library': typeof LibraryIndexRoute
  '/library/$id/edit': typeof LibraryIdEditRoute
  '/library/$id': typeof LibraryIdIndexRoute
  '/present/$code': typeof PresentCodeIndexRoute
  '/view/$code': typeof ViewCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/session': typeof SessionRoute
  '/library/new': typeof LibraryNewRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/library/': typeof LibraryIndexRoute
  '/library/$id/edit': typeof LibraryIdEditRoute
  '/library/$id/': typeof LibraryIdIndexRoute
  '/present/$code/': typeof PresentCodeIndexRoute
  '/view/$code/': typeof ViewCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/playlists'
    | '/session'
    | '/library/new'
    | '/playlists/$id'
    | '/library'
    | '/library/$id/edit'
    | '/library/$id'
    | '/present/$code'
    | '/view/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/playlists'
    | '/session'
    | '/library/new'
    | '/playlists/$id'
    | '/library'
    | '/library/$id/edit'
    | '/library/$id'
    | '/present/$code'
    | '/view/$code'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/playlists'
    | '/session'
    | '/library/new'
    | '/playlists/$id'
    | '/library/'
    | '/library/$id/edit'
    | '/library/$id/'
    | '/present/$code/'
    | '/view/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PlaylistsRoute: typeof PlaylistsRouteWithChildren
  SessionRoute: typeof SessionRoute
  LibraryNewRoute: typeof LibraryNewRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  LibraryIdEditRoute: typeof LibraryIdEditRoute
  LibraryIdIndexRoute: typeof LibraryIdIndexRoute
  PresentCodeIndexRoute: typeof PresentCodeIndexRoute
  ViewCodeIndexRoute: typeof ViewCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$id': {
      id: '/playlists/$id'
      path: '/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof PlaylistsIdRouteImport
      parentRoute: typeof PlaylistsRoute
    }
    '/library/new': {
      id: '/library/new'
      path: '/library/new'
      fullPath: '/library/new'
      preLoaderRoute: typeof LibraryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$code/': {
      id: '/view/$code/'
      path: '/view/$code'
      fullPath: '/view/$code'
      preLoaderRoute: typeof ViewCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$code/': {
      id: '/present/$code/'
      path: '/present/$code'
      fullPath: '/present/$code'
      preLoaderRoute: typeof PresentCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$id/': {
      id: '/library/$id/'
      path: '/library/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$id/edit': {
      id: '/library/$id/edit'
      path: '/library/$id/edit'
      fullPath: '/library/$id/edit'
      preLoaderRoute: typeof LibraryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlaylistsRouteChildren {
  PlaylistsIdRoute: typeof PlaylistsIdRoute
}

const PlaylistsRouteChildren: PlaylistsRouteChildren = {
  PlaylistsIdRoute: PlaylistsIdRoute,
}

const PlaylistsRouteWithChildren = PlaylistsRoute._addFileChildren(
  PlaylistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PlaylistsRoute: PlaylistsRouteWithChildren,
  SessionRoute: SessionRoute,
  LibraryNewRoute: LibraryNewRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  LibraryIdEditRoute: LibraryIdEditRoute,
  LibraryIdIndexRoute: LibraryIdIndexRoute,
  PresentCodeIndexRoute: PresentCodeIndexRoute,
  ViewCodeIndexRoute: ViewCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
