/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TunerRouteImport } from './routes/tuner'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SessionRouteImport } from './routes/session'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExtractRouteImport } from './routes/extract'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as LibraryNewRouteImport } from './routes/library/new'
import { Route as DebugSongEditorRouteImport } from './routes/debug/song-editor'
import { Route as ViewCodeIndexRouteImport } from './routes/view/$code/index'
import { Route as PresentCodeIndexRouteImport } from './routes/present/$code/index'
import { Route as LibraryIdIndexRouteImport } from './routes/library/$id/index'
import { Route as LibraryIdEditRouteImport } from './routes/library/$id/edit'

const TunerRoute = TunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractRoute = ExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryNewRoute = LibraryNewRouteImport.update({
  id: '/library/new',
  path: '/library/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugSongEditorRoute = DebugSongEditorRouteImport.update({
  id: '/debug/song-editor',
  path: '/debug/song-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewCodeIndexRoute = ViewCodeIndexRouteImport.update({
  id: '/view/$code/',
  path: '/view/$code/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentCodeIndexRoute = PresentCodeIndexRouteImport.update({
  id: '/present/$code/',
  path: '/present/$code/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdIndexRoute = LibraryIdIndexRouteImport.update({
  id: '/library/$id/',
  path: '/library/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdEditRoute = LibraryIdEditRouteImport.update({
  id: '/library/$id/edit',
  path: '/library/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/extract': typeof ExtractRoute
  '/login': typeof LoginRoute
  '/playlists': typeof PlaylistsRoute
  '/session': typeof SessionRoute
  '/sessions': typeof SessionsRoute
  '/studio': typeof StudioRoute
  '/tuner': typeof TunerRoute
  '/debug/song-editor': typeof DebugSongEditorRoute
  '/library/new': typeof LibraryNewRoute
  '/library/': typeof LibraryIndexRoute
  '/library/$id/edit': typeof LibraryIdEditRoute
  '/library/$id/': typeof LibraryIdIndexRoute
  '/present/$code/': typeof PresentCodeIndexRoute
  '/view/$code/': typeof ViewCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/extract': typeof ExtractRoute
  '/login': typeof LoginRoute
  '/playlists': typeof PlaylistsRoute
  '/session': typeof SessionRoute
  '/sessions': typeof SessionsRoute
  '/studio': typeof StudioRoute
  '/tuner': typeof TunerRoute
  '/debug/song-editor': typeof DebugSongEditorRoute
  '/library/new': typeof LibraryNewRoute
  '/library': typeof LibraryIndexRoute
  '/library/$id/edit': typeof LibraryIdEditRoute
  '/library/$id': typeof LibraryIdIndexRoute
  '/present/$code': typeof PresentCodeIndexRoute
  '/view/$code': typeof ViewCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/extract': typeof ExtractRoute
  '/login': typeof LoginRoute
  '/playlists': typeof PlaylistsRoute
  '/session': typeof SessionRoute
  '/sessions': typeof SessionsRoute
  '/studio': typeof StudioRoute
  '/tuner': typeof TunerRoute
  '/debug/song-editor': typeof DebugSongEditorRoute
  '/library/new': typeof LibraryNewRoute
  '/library/': typeof LibraryIndexRoute
  '/library/$id/edit': typeof LibraryIdEditRoute
  '/library/$id/': typeof LibraryIdIndexRoute
  '/present/$code/': typeof PresentCodeIndexRoute
  '/view/$code/': typeof ViewCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/extract'
    | '/login'
    | '/playlists'
    | '/session'
    | '/sessions'
    | '/studio'
    | '/tuner'
    | '/debug/song-editor'
    | '/library/new'
    | '/library/'
    | '/library/$id/edit'
    | '/library/$id/'
    | '/present/$code/'
    | '/view/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/extract'
    | '/login'
    | '/playlists'
    | '/session'
    | '/sessions'
    | '/studio'
    | '/tuner'
    | '/debug/song-editor'
    | '/library/new'
    | '/library'
    | '/library/$id/edit'
    | '/library/$id'
    | '/present/$code'
    | '/view/$code'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/extract'
    | '/login'
    | '/playlists'
    | '/session'
    | '/sessions'
    | '/studio'
    | '/tuner'
    | '/debug/song-editor'
    | '/library/new'
    | '/library/'
    | '/library/$id/edit'
    | '/library/$id/'
    | '/present/$code/'
    | '/view/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExtractRoute: typeof ExtractRoute
  LoginRoute: typeof LoginRoute
  PlaylistsRoute: typeof PlaylistsRoute
  SessionRoute: typeof SessionRoute
  SessionsRoute: typeof SessionsRoute
  StudioRoute: typeof StudioRoute
  TunerRoute: typeof TunerRoute
  DebugSongEditorRoute: typeof DebugSongEditorRoute
  LibraryNewRoute: typeof LibraryNewRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  LibraryIdEditRoute: typeof LibraryIdEditRoute
  LibraryIdIndexRoute: typeof LibraryIdIndexRoute
  PresentCodeIndexRoute: typeof PresentCodeIndexRoute
  ViewCodeIndexRoute: typeof ViewCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tuner': {
      id: '/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof TunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract': {
      id: '/extract'
      path: '/extract'
      fullPath: '/extract'
      preLoaderRoute: typeof ExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/new': {
      id: '/library/new'
      path: '/library/new'
      fullPath: '/library/new'
      preLoaderRoute: typeof LibraryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/song-editor': {
      id: '/debug/song-editor'
      path: '/debug/song-editor'
      fullPath: '/debug/song-editor'
      preLoaderRoute: typeof DebugSongEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$code/': {
      id: '/view/$code/'
      path: '/view/$code'
      fullPath: '/view/$code/'
      preLoaderRoute: typeof ViewCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$code/': {
      id: '/present/$code/'
      path: '/present/$code'
      fullPath: '/present/$code/'
      preLoaderRoute: typeof PresentCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$id/': {
      id: '/library/$id/'
      path: '/library/$id'
      fullPath: '/library/$id/'
      preLoaderRoute: typeof LibraryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$id/edit': {
      id: '/library/$id/edit'
      path: '/library/$id/edit'
      fullPath: '/library/$id/edit'
      preLoaderRoute: typeof LibraryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExtractRoute: ExtractRoute,
  LoginRoute: LoginRoute,
  PlaylistsRoute: PlaylistsRoute,
  SessionRoute: SessionRoute,
  SessionsRoute: SessionsRoute,
  StudioRoute: StudioRoute,
  TunerRoute: TunerRoute,
  DebugSongEditorRoute: DebugSongEditorRoute,
  LibraryNewRoute: LibraryNewRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  LibraryIdEditRoute: LibraryIdEditRoute,
  LibraryIdIndexRoute: LibraryIdIndexRoute,
  PresentCodeIndexRoute: PresentCodeIndexRoute,
  ViewCodeIndexRoute: ViewCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
